M3l1 spring
otuskotlin/202306-ok-marketplace pull request #16
Opened 2023-08-20 18:01 UTC by evgnep

2023-08-22 05:52 UTC, svok requested changes

2023-08-22 05:52 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v1/controller/AdController.kt
> +class AdController(private val processor: MkplAdProcessor) {
appSettings здесь должен быть

2023-08-22 05:52 UTC, svok commented on ok-marketplace-mappers-v1/src/main/kotlin/MappersV1ToTransport.kt
> +    responseType = "read",
Это зачем?
Мы до этого отлично справлялись без этого свойства и я намерен продолжать жить без него.
Тем более, что ты здесь сделал строковое свойство.

2023-08-22 05:52 UTC, svok commented on ok-marketplace-mappers-v1/src/main/kotlin/MappersV1ToTransport.kt
> +    responseType = "read",
У нас в других версиях было похожее свойство. 
Называлось command
И было не строковым, а энумом.

2023-08-27 17:19 UTC, evgnep commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v1/controller/AdController.kt
> +class AdController(private val processor: MkplAdProcessor) {
должен, но не в этом занятии - глянь 2212, там его нет
И я считаю, тут ему не место на данном этапе - смысла в нем сейчас нет, плюс эти переделки вылезут проблемами на следующих занятиях

2023-08-27 17:21 UTC, evgnep commented on ok-marketplace-mappers-v1/src/main/kotlin/MappersV1ToTransport.kt
> +    responseType = "read",
без этого не работают тесты, видимо что-то сломали на занятии про мапперы

val expectedResponse = mapper.writeValueAsString(responseObj as IResponse)

вот такое дает `{"responseType":"create","result":"error","ad":{}}`, без поля типа

2023-08-27 17:30 UTC, evgnep commented on ok-marketplace-mappers-v1/src/main/kotlin/MappersV1ToTransport.kt
> +    responseType = "read",
готово

2023-09-03 05:15 UTC, merged